### ISSUE TITLE
"bundle install", fedora 28, fails fetching https://github.com/asciidoctor/asciidoctor-epub3

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#1068]
Not sure if this is the proper place to submit a build issue, but on my Fedora 28 system, if I run "bundle install", I get:

```
$ bundle install
Fetching https://github.com/asciidoctor/asciidoctor-epub3
error: cannot open .git/FETCH_HEAD: Permission denied

Retrying `git fetch --force --quiet --tags "/home/rpjday/.bundle/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18"` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags "/home/rpjday/.bundle/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18"` in directory /usr/share/gems/bundler/gems/asciidoctor-epub3-ba930925a1df has failed.
If this error persists you could try removing the cache directory '/home/rpjday/.bundle/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18'error: cannot open .git/FETCH_HEAD: Permission denied

Retrying `git fetch --force --quiet --tags "/home/rpjday/.bundle/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18"` due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags "/home/rpjday/.bundle/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18"` in directory /usr/share/gems/bundler/gems/asciidoctor-epub3-ba930925a1df has failed.
If this error persists you could try removing the cache directory '/home/rpjday/.bundle/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18'error: cannot open .git/FETCH_HEAD: Permission denied

Retrying `git fetch --force --quiet --tags "/home/rpjday/.bundle/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18"` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags "/home/rpjday/.bundle/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18"` in directory /usr/share/gems/bundler/gems/asciidoctor-epub3-ba930925a1df has failed.
If this error persists you could try removing the cache directory '/home/rpjday/.bundle/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18'error: cannot open .git/FETCH_HEAD: Permission denied

Git error: command `git fetch --force --quiet --tags
"/home/rpjday/.bundle/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18"` in directory
/usr/share/gems/bundler/gems/asciidoctor-epub3-ba930925a1df has failed.
If this error persists you could try removing the cache directory
'/home/rpjday/.bundle/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18'

```

Since I'm interested only in PDF, I commented out the line from Gemfile to generate epub3, and all works fine. Is there something I need to change about my system setup to resolve this?

**Comment by krisfremen** [comment]
This looks like a local permission error.

Did you clone as root and maybe doing the bundle install as a regular user?

**Comment by rpjday** [comment]
I cloned the original repo as a regular user (always!), I'm not adequately familiar with Ruby to know what needs to be done as root or as a regular user.

**Comment by aollier** [comment]
Same problem now with Fedora 31:
```console
$ sudo bundle install
[sudo] Mot de passe de aollier : 
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Fetching https://github.com/asciidoctor/asciidoctor-epub3
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 13.0.1
Using Ascii85 1.0.3
Using public_suffix 4.0.1
Using afm 0.2.2
Using asciidoctor 1.5.6.1
Using concurrent-ruby 1.1.5
Using mini_portile2 2.4.0
Using rubyzip 2.0.0
Using thread_safe 0.3.6
Using pdf-core 0.7.0
Using ttfunk 1.5.1
Using hashery 2.1.2
Using ruby-rc4 0.1.5
Using safe_yaml 1.0.5
Using polyglot 0.3.5
Using awesome_print 1.8.0
Using coderay 1.1.2
Using epubcheck 3.0.1
Using json 2.3.0
Using multi_json 1.14.1
Using bundler 1.11.2
Using addressable 2.7.0
Using nokogiri 1.10.7
Using kindlegen 3.0.4
Using prawn 2.2.2
Using pdf-reader 2.4.0
Using treetop 1.5.3
Using pygments.rb 1.2.1
Using css_parser 1.7.1
Using gepub 1.0.6
Using prawn-icon 1.3.0
Using prawn-table 0.2.2
Using prawn-templates 0.1.1
Using prawn-svg 0.27.1
Using asciidoctor-epub3 1.5.0.alpha.10.dev from https://github.com/asciidoctor/asciidoctor-epub3 (at master@c8ca2e2)

NoMethodError: undefined method `[]' for nil:NilClass
Using asciidoctor-pdf 1.5.0.alpha.16
An error occurred while installing asciidoctor-epub3 (1.5.0.alpha.10.dev), and Bundler cannot continue.
```
Ruby version:
```console
$ ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
```

**Comment by aollier** [comment]
I changed my Gemfile like this:
```diff
diff --git a/Gemfile b/Gemfile
index 4ecffb4..345ae22 100644
--- a/Gemfile
+++ b/Gemfile
@@ -1,13 +1,13 @@
 source 'https://rubygems.org'
 
 gem 'rake'
-gem 'asciidoctor', '1.5.6.1'
+gem 'asciidoctor', '~> 2.0', '>= 2.0.10'
 
 gem 'json'
 gem 'awesome_print'
 
-gem 'asciidoctor-epub3', :git => 'https://github.com/asciidoctor/asciidoctor-epub3'
-gem 'asciidoctor-pdf', '1.5.0.alpha.16'
+gem 'asciidoctor-epub3', '~> 1.5.0.alpha.9'
+gem 'asciidoctor-pdf', '~> 1.5.0.beta.8'
 
 gem 'coderay'
 gem 'pygments.rb'
```
Now `bundle install` works fine:
```console
$ sudo bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 13.0.1
Using Ascii85 1.0.3
Using public_suffix 4.0.1
Using afm 0.2.2
Using asciidoctor 2.0.10
Using concurrent-ruby 1.1.5
Using mini_portile2 2.4.0
Using rubyzip 2.0.0
Using thread_safe 0.3.6
Using pdf-core 0.7.0
Using ttfunk 1.5.1
Using hashery 2.1.2
Using ruby-rc4 0.1.5
Using safe_yaml 1.0.5
Using polyglot 0.3.5
Using awesome_print 1.8.0
Using coderay 1.1.2
Using epubcheck 3.0.1
Using json 2.3.0
Using multi_json 1.14.1
Using bundler 1.11.2
Using addressable 2.7.0
Using nokogiri 1.10.7
Using kindlegen 3.0.4
Using prawn 2.2.2
Using pdf-reader 2.4.0
Using treetop 1.5.3
Using pygments.rb 1.2.1
Using css_parser 1.7.1
Using gepub 1.0.6
Using prawn-icon 2.5.0
Using prawn-table 0.2.2
Using prawn-templates 0.1.2
Using prawn-svg 0.30.0
Installing asciidoctor-epub3 1.5.0.alpha.9
Using asciidoctor-pdf 1.5.0.beta.8
Bundle complete! 11 Gemfile dependencies, 36 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```
But now `bundle exec rake book:build` fails:
```console
$ bundle exec rake book:build
Ignoring json-2.1.0 because its extensions are not built. Try: gem pristine json --version 2.1.0
Ignoring json-2.0.4 because its extensions are not built. Try: gem pristine json --version 2.0.4
Ignoring json-2.0.3 because its extensions are not built. Try: gem pristine json --version 2.0.3
Ignoring json-2.0.2 because its extensions are not built. Try: gem pristine json --version 2.0.2
Ignoring kindlegen-3.0.3 because its extensions are not built. Try: gem pristine kindlegen --version 3.0.3
Ignoring kindlegen-3.0.2 because its extensions are not built. Try: gem pristine kindlegen --version 3.0.2
Ignoring kindlegen-3.0.1 because its extensions are not built. Try: gem pristine kindlegen --version 3.0.1
Ignoring kindlegen-2.9.7 because its extensions are not built. Try: gem pristine kindlegen --version 2.9.7
Ignoring kindlegen-2.9.6 because its extensions are not built. Try: gem pristine kindlegen --version 2.9.6
Ignoring nokogiri-1.6.8.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.8.1
Ignoring nokogiri-1.6.8 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.8
Ignoring nokogiri-1.6.7.2 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.7.2
Ignoring nokogiri-1.6.7.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.7.1
Ignoring posix-spawn-0.3.12 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.12
Ignoring posix-spawn-0.3.11 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.11
Ignoring posix-spawn-0.3.9 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.9
Ignoring json-2.1.0 because its extensions are not built. Try: gem pristine json --version 2.1.0
Ignoring json-2.0.4 because its extensions are not built. Try: gem pristine json --version 2.0.4
Ignoring json-2.0.3 because its extensions are not built. Try: gem pristine json --version 2.0.3
Ignoring json-2.0.2 because its extensions are not built. Try: gem pristine json --version 2.0.2
Ignoring kindlegen-3.0.3 because its extensions are not built. Try: gem pristine kindlegen --version 3.0.3
Ignoring kindlegen-3.0.2 because its extensions are not built. Try: gem pristine kindlegen --version 3.0.2
Ignoring kindlegen-3.0.1 because its extensions are not built. Try: gem pristine kindlegen --version 3.0.1
Ignoring kindlegen-2.9.7 because its extensions are not built. Try: gem pristine kindlegen --version 2.9.7
Ignoring kindlegen-2.9.6 because its extensions are not built. Try: gem pristine kindlegen --version 2.9.6
Ignoring nokogiri-1.6.8.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.8.1
Ignoring nokogiri-1.6.8 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.8
Ignoring nokogiri-1.6.7.2 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.7.2
Ignoring nokogiri-1.6.7.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.7.1
Ignoring posix-spawn-0.3.12 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.12
Ignoring posix-spawn-0.3.11 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.11
Ignoring posix-spawn-0.3.9 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.9
Traceback (most recent call last):
        20: from /usr/bin/rake:23:in `<main>'
        19: from /usr/share/rubygems/rubygems.rb:303:in `activate_bin_path'
        18: from /usr/share/rubygems/rubygems.rb:303:in `synchronize'
        17: from /usr/share/rubygems/rubygems.rb:305:in `block in activate_bin_path'
        16: from /usr/share/rubygems/rubygems.rb:242:in `finish_resolve'
        15: from /usr/share/rubygems/rubygems/request_set.rb:435:in `resolve_current'
        14: from /usr/share/rubygems/rubygems/request_set.rb:423:in `resolve'
        13: from /usr/share/rubygems/rubygems/resolver.rb:188:in `resolve'
        12: from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
        11: from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:64:in `resolve'
        10: from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:106:in `start_resolution'
         9: from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:165:in `initial_state'
         8: from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:51:in `sort_dependencies'
         7: from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
         6: from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_dependencies'
         5: from /usr/share/rubygems/rubygems/resolver.rb:277:in `sort_dependencies'
         4: from /usr/share/rubygems/rubygems/resolver.rb:277:in `with_index'
         3: from /usr/share/rubygems/rubygems/resolver.rb:277:in `sort_by'
         2: from /usr/share/rubygems/rubygems/resolver.rb:277:in `each'
         1: from /usr/share/rubygems/rubygems/resolver.rb:283:in `block in sort_dependencies'
/usr/share/rubygems/rubygems/resolver.rb:231:in `search_for': Unable to resolve dependency: user requested 'did_you_mean (= 1.3.0)' (Gem::UnsatisfiableDependencyError)
```

May someone help?

**Comment by aollier** [comment]
Removing the cache in '/home/aollier/.bundler/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18' makes the first error disappear, but not the problem of building the book:
```console
$ rm -rf ~/.bundler/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18/
$ bundle install
Ignoring json-2.1.0 because its extensions are not built. Try: gem pristine json --version 2.1.0
Ignoring json-2.0.4 because its extensions are not built. Try: gem pristine json --version 2.0.4
Ignoring json-2.0.3 because its extensions are not built. Try: gem pristine json --version 2.0.3
Ignoring json-2.0.2 because its extensions are not built. Try: gem pristine json --version 2.0.2
Ignoring kindlegen-3.0.3 because its extensions are not built. Try: gem pristine kindlegen --version 3.0.3
Ignoring kindlegen-3.0.2 because its extensions are not built. Try: gem pristine kindlegen --version 3.0.2
Ignoring kindlegen-3.0.1 because its extensions are not built. Try: gem pristine kindlegen --version 3.0.1
Ignoring kindlegen-2.9.7 because its extensions are not built. Try: gem pristine kindlegen --version 2.9.7
Ignoring kindlegen-2.9.6 because its extensions are not built. Try: gem pristine kindlegen --version 2.9.6
Ignoring nokogiri-1.6.8.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.8.1
Ignoring nokogiri-1.6.8 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.8
Ignoring nokogiri-1.6.7.2 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.7.2
Ignoring nokogiri-1.6.7.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.7.1
Ignoring posix-spawn-0.3.12 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.12
Ignoring posix-spawn-0.3.11 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.11
Ignoring posix-spawn-0.3.9 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.9
Using rake 13.0.1
Using Ascii85 1.0.3
Using public_suffix 4.0.1
Using afm 0.2.2
Using asciidoctor 2.0.10
Using concurrent-ruby 1.1.5
Using mini_portile2 2.4.0
Using rubyzip 2.0.0
Using thread_safe 0.3.6
Using pdf-core 0.7.0
Using ttfunk 1.5.1
Using hashery 2.1.2
Using ruby-rc4 0.1.5
Using safe_yaml 1.0.5
Using polyglot 0.3.5
Using awesome_print 1.8.0
Using coderay 1.1.2
Using epubcheck 3.0.1
Using json 2.3.0
Using multi_json 1.14.1
Using bundler 1.11.2
Using addressable 2.7.0
Using nokogiri 1.10.7
Using kindlegen 3.0.4
Using prawn 2.2.2
Using pdf-reader 2.4.0
Using treetop 1.5.3
Using pygments.rb 1.2.1
Using css_parser 1.7.1
Using gepub 1.0.6
Using prawn-icon 2.5.0
Using prawn-table 0.2.2
Using prawn-templates 0.1.2
Using prawn-svg 0.30.0
Using asciidoctor-epub3 1.5.0.alpha.9
Using asciidoctor-pdf 1.5.0.beta.8
Bundle complete! 11 Gemfile dependencies, 36 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ bundle exec rake book:build
Ignoring json-2.1.0 because its extensions are not built. Try: gem pristine json --version 2.1.0
Ignoring json-2.0.4 because its extensions are not built. Try: gem pristine json --version 2.0.4
Ignoring json-2.0.3 because its extensions are not built. Try: gem pristine json --version 2.0.3
Ignoring json-2.0.2 because its extensions are not built. Try: gem pristine json --version 2.0.2
Ignoring kindlegen-3.0.3 because its extensions are not built. Try: gem pristine kindlegen --version 3.0.3
Ignoring kindlegen-3.0.2 because its extensions are not built. Try: gem pristine kindlegen --version 3.0.2
Ignoring kindlegen-3.0.1 because its extensions are not built. Try: gem pristine kindlegen --version 3.0.1
Ignoring kindlegen-2.9.7 because its extensions are not built. Try: gem pristine kindlegen --version 2.9.7
Ignoring kindlegen-2.9.6 because its extensions are not built. Try: gem pristine kindlegen --version 2.9.6
Ignoring nokogiri-1.6.8.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.8.1
Ignoring nokogiri-1.6.8 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.8
Ignoring nokogiri-1.6.7.2 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.7.2
Ignoring nokogiri-1.6.7.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.7.1
Ignoring posix-spawn-0.3.12 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.12
Ignoring posix-spawn-0.3.11 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.11
Ignoring posix-spawn-0.3.9 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.9
Ignoring json-2.1.0 because its extensions are not built. Try: gem pristine json --version 2.1.0
Ignoring json-2.0.4 because its extensions are not built. Try: gem pristine json --version 2.0.4
Ignoring json-2.0.3 because its extensions are not built. Try: gem pristine json --version 2.0.3
Ignoring json-2.0.2 because its extensions are not built. Try: gem pristine json --version 2.0.2
Ignoring kindlegen-3.0.3 because its extensions are not built. Try: gem pristine kindlegen --version 3.0.3
Ignoring kindlegen-3.0.2 because its extensions are not built. Try: gem pristine kindlegen --version 3.0.2
Ignoring kindlegen-3.0.1 because its extensions are not built. Try: gem pristine kindlegen --version 3.0.1
Ignoring kindlegen-2.9.7 because its extensions are not built. Try: gem pristine kindlegen --version 2.9.7
Ignoring kindlegen-2.9.6 because its extensions are not built. Try: gem pristine kindlegen --version 2.9.6
Ignoring nokogiri-1.6.8.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.8.1
Ignoring nokogiri-1.6.8 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.8
Ignoring nokogiri-1.6.7.2 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.7.2
Ignoring nokogiri-1.6.7.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.7.1
Ignoring posix-spawn-0.3.12 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.12
Ignoring posix-spawn-0.3.11 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.11
Ignoring posix-spawn-0.3.9 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.9
Traceback (most recent call last):
        20: from /usr/bin/rake:23:in `<main>'
        19: from /usr/share/rubygems/rubygems.rb:303:in `activate_bin_path'
        18: from /usr/share/rubygems/rubygems.rb:303:in `synchronize'
        17: from /usr/share/rubygems/rubygems.rb:305:in `block in activate_bin_path'
        16: from /usr/share/rubygems/rubygems.rb:242:in `finish_resolve'
        15: from /usr/share/rubygems/rubygems/request_set.rb:435:in `resolve_current'
        14: from /usr/share/rubygems/rubygems/request_set.rb:423:in `resolve'
        13: from /usr/share/rubygems/rubygems/resolver.rb:188:in `resolve'
        12: from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
        11: from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:64:in `resolve'
        10: from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:106:in `start_resolution'
         9: from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:165:in `initial_state'
         8: from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:51:in `sort_dependencies'
         7: from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
         6: from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_dependencies'
         5: from /usr/share/rubygems/rubygems/resolver.rb:277:in `sort_dependencies'
         4: from /usr/share/rubygems/rubygems/resolver.rb:277:in `with_index'
         3: from /usr/share/rubygems/rubygems/resolver.rb:277:in `sort_by'
         2: from /usr/share/rubygems/rubygems/resolver.rb:277:in `each'
         1: from /usr/share/rubygems/rubygems/resolver.rb:283:in `block in sort_dependencies'
/usr/share/rubygems/rubygems/resolver.rb:231:in `search_for': Unable to resolve dependency: user requested 'did_you_mean (= 1.3.0)' (Gem::UnsatisfiableDependencyError)
```

**Comment by aollier** [comment]
Advices for gems with extensions not built do not work:
```bash
for jso_version in 2.1.0 2.0.{4..2}
do
    sudo gem pristine json --version $json_version
done
```
```console
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["json"] = 2.1.0
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["json"] = 2.0.4
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["json"] = 2.0.3
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["json"] = 2.0.2
```
```bash
for kindlegen_version in 3.0.{3..1} 2.9.{7,6}
do
    sudo gem pristine kindlegen --version $kindlegen_version
done
```
```console
Restoring gems to pristine condition...
Building native extensions. This could take a while...
Restored kindlegen-3.0.3
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["kindlegen"] = 3.0.2
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["kindlegen"] = 3.0.1
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["kindlegen"] = 2.9.7
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["kindlegen"] = 2.9.6
```
```bash
for nokogiri_version in 1.6.8{.1,} 1.6.7.{2,1}
do
    sudo gem pristine nokogiri --version $nokogiri_version
done
```
```console
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["nokogiri"] = 1.6.8.1
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["nokogiri"] = 1.6.8
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["nokogiri"] = 1.6.7.2
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["nokogiri"] = 1.6.7.1
```
```bash
for posixspawn_version in 0.3.{12,11,9}
do
    sudo gem pristine posix-spawn --version $posixspawn_version
done
```
```console
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["posix-spawn"] = 0.3.12
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["posix-spawn"] = 0.3.11
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["posix-spawn"] = 0.3.9
```

**Comment by aollier** [comment]
Here is my Gemfile.lock:
```console
$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    Ascii85 (1.0.3)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    afm (0.2.2)
    asciidoctor (2.0.10)
    asciidoctor-epub3 (1.5.0.alpha.9)
      asciidoctor (>= 1.5.0, < 3.0.0)
      concurrent-ruby (~> 1.1.5)
      gepub (~> 1.0.2)
      thread_safe (~> 0.3.6)
    asciidoctor-pdf (1.5.0.beta.8)
      asciidoctor (>= 1.5.3, < 3.0.0)
      concurrent-ruby (~> 1.1.0)
      prawn (~> 2.2.0)
      prawn-icon (~> 2.5.0)
      prawn-svg (~> 0.30.0)
      prawn-table (~> 0.2.0)
      prawn-templates (~> 0.1.0)
      safe_yaml (~> 1.0.0)
      thread_safe (~> 0.3.0)
      treetop (~> 1.5.0)
    awesome_print (1.8.0)
    coderay (1.1.2)
    concurrent-ruby (1.1.5)
    css_parser (1.7.1)
      addressable
    epubcheck (3.0.1)
    gepub (1.0.6)
      nokogiri (>= 1.8.2, < 1.11)
      rubyzip (> 1.1.1, < 2.1)
    hashery (2.1.2)
    json (2.3.0)
    kindlegen (3.0.4)
      rake
      rubyzip
    mini_portile2 (2.4.0)
    multi_json (1.14.1)
    nokogiri (1.10.7)
      mini_portile2 (~> 2.4.0)
    pdf-core (0.7.0)
    pdf-reader (2.4.0)
      Ascii85 (~> 1.0.0)
      afm (~> 0.2.1)
      hashery (~> 2.0)
      ruby-rc4
      ttfunk
    polyglot (0.3.5)
    prawn (2.2.2)
      pdf-core (~> 0.7.0)
      ttfunk (~> 1.5)
    prawn-icon (2.5.0)
      prawn (>= 1.1.0, < 3.0.0)
    prawn-svg (0.30.0)
      css_parser (~> 1.6)
      prawn (>= 0.11.1, < 3)
    prawn-table (0.2.2)
      prawn (>= 1.3.0, < 3.0.0)
    prawn-templates (0.1.2)
      pdf-reader (~> 2.0)
      prawn (~> 2.2)
    public_suffix (4.0.1)
    pygments.rb (1.2.1)
      multi_json (>= 1.0.0)
    rake (13.0.1)
    ruby-rc4 (0.1.5)
    rubyzip (2.0.0)
    safe_yaml (1.0.5)
    thread_safe (0.3.6)
    treetop (1.5.3)
      polyglot (~> 0.3)
    ttfunk (1.5.1)

PLATFORMS
  ruby

DEPENDENCIES
  asciidoctor (~> 2.0, >= 2.0.10)
  asciidoctor-epub3 (~> 1.5.0.alpha.9)
  asciidoctor-pdf (~> 1.5.0.beta.8)
  awesome_print
  coderay
  epubcheck
  json
  kindlegen
  pygments.rb
  rake
  thread_safe

BUNDLED WITH
   1.11.2
```

**Comment by aollier** [comment]
I finally resolved my problem: it was necessary to upgrade Bundler.
```bash
$ rm Gemfile.lock
$ sudo gem install rubygems-update
$ sudo update_rubygems
$ sudo gem update --system
$ bundle install
$ sudo gem pristine kindlegen --version 3.0.5
$ bundle install
$ bundle exec rake book:build
```
For the initial problem of @rpjday, it is necessary to do following command:
```bash
$ rm -rf ~/.bundle/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18
```
Here is my new Gemfile.lock:
```console
$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    Ascii85 (1.0.3)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    afm (0.2.2)
    asciidoctor (2.0.10)
    asciidoctor-epub3 (1.5.0.alpha.9)
      asciidoctor (>= 1.5.0, < 3.0.0)
      concurrent-ruby (~> 1.1.5)
      gepub (~> 1.0.2)
      thread_safe (~> 0.3.6)
    asciidoctor-pdf (1.5.0.beta.8)
      asciidoctor (>= 1.5.3, < 3.0.0)
      concurrent-ruby (~> 1.1.0)
      prawn (~> 2.2.0)
      prawn-icon (~> 2.5.0)
      prawn-svg (~> 0.30.0)
      prawn-table (~> 0.2.0)
      prawn-templates (~> 0.1.0)
      safe_yaml (~> 1.0.0)
      thread_safe (~> 0.3.0)
      treetop (~> 1.5.0)
    awesome_print (1.8.0)
    coderay (1.1.2)
    concurrent-ruby (1.1.5)
    css_parser (1.7.1)
      addressable
    epubcheck (3.0.1)
    gepub (1.0.6)
      nokogiri (>= 1.8.2, < 1.11)
      rubyzip (> 1.1.1, < 2.1)
    hashery (2.1.2)
    json (2.3.0)
    kindlegen (3.0.5)
      rake
      rubyzip
    mini_portile2 (2.4.0)
    multi_json (1.14.1)
    nokogiri (1.10.7)
      mini_portile2 (~> 2.4.0)
    pdf-core (0.7.0)
    pdf-reader (2.4.0)
      Ascii85 (~> 1.0.0)
      afm (~> 0.2.1)
      hashery (~> 2.0)
      ruby-rc4
      ttfunk
    polyglot (0.3.5)
    prawn (2.2.2)
      pdf-core (~> 0.7.0)
      ttfunk (~> 1.5)
    prawn-icon (2.5.0)
      prawn (>= 1.1.0, < 3.0.0)
    prawn-svg (0.30.0)
      css_parser (~> 1.6)
      prawn (>= 0.11.1, < 3)
    prawn-table (0.2.2)
      prawn (>= 1.3.0, < 3.0.0)
    prawn-templates (0.1.2)
      pdf-reader (~> 2.0)
      prawn (~> 2.2)
    public_suffix (4.0.1)
    pygments.rb (1.2.1)
      multi_json (>= 1.0.0)
    rake (13.0.1)
    ruby-rc4 (0.1.5)
    rubyzip (2.0.0)
    safe_yaml (1.0.5)
    thread_safe (0.3.6)
    treetop (1.5.3)
      polyglot (~> 0.3)
    ttfunk (1.5.1)

PLATFORMS
  ruby

DEPENDENCIES
  asciidoctor (~> 2.0, >= 2.0.10)
  asciidoctor-epub3 (~> 1.5.0.alpha.9)
  asciidoctor-pdf (~> 1.5.0.beta.8)
  awesome_print
  coderay
  epubcheck
  json
  kindlegen
  pygments.rb
  rake
  thread_safe

BUNDLED WITH
   2.1.2
```
